const sampleData = {
  "floral_arrangements": [
    {
      "slug": "rose-elegance-bouquet",
      "name": "Rose Elegance Bouquet",
      "price": 35,
      "description": "A stunning arrangement featuring fresh red roses.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["Red", "Green"],
      "occasion_ids": [1, 2, 3],
      "ratings_id": 1,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "sunflower-sunshine-bunch",
      "name": "Sunflower Sunshine Bunch",
      "price": 28,
      "description": "Bright yellow sunflowers arranged for a cheerful gift.",
      "category": "Bunch",
      "type_id": 1,
      "colors": ["Yellow", "Green"],
      "occasion_ids": [4, 5],
      "ratings_id": 2,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "pure-white-lily-grace",
      "name": "Pure White Lily Grace",
      "price": 42,
      "description": "An all-white lily bouquet symbolizing elegance.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["White", "Green"],
      "occasion_ids": [6, 7, 3],
      "ratings_id": 3,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "pink-petal-romance-bunch",
      "name": "Pink Petal Romance Bunch",
      "price": 30,
      "description": "A charming collection of pink flowers.",
      "category": "Bunch",
      "type_id": 1,
      "colors": ["Pink", "Green"],
      "occasion_ids": [2, 8, 4],
      "ratings_id": 4,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "bright-carnival-bouquet",
      "name": "Bright Carnival Bouquet",
      "price": 25,
      "description": "Daisies and carnations in a playful mix of colors.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["Yellow", "Pink", "White", "Green"],
      "occasion_ids": [4, 5, 9],
      "ratings_id": 5,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "tropical-paradise-arrangement",
      "name": "Tropical Paradise Arrangement",
      "price": 70,
      "description": "Exotic flowers like Bird of Paradise and Heliconia.",
      "category": "Arrangement",
      "type_id": 1,
      "colors": ["Orange", "Yellow", "Green", "Red"],
      "occasion_ids": [9, 10, 4],
      "ratings_id": 6,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "sweetheart-rose-lily-combo",
      "name": "Sweetheart Rose & Lily Combo",
      "price": 48,
      "description": "A romantic mix of red roses and white lilies.",
      "category": "Combo",
      "type_id": 4,
      "colors": ["Red", "White", "Green"],
      "occasion_ids": [2, 1, 3],
      "ratings_id": 7,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "golden-sunset-sunflower-bunch",
      "name": "Golden Sunset Sunflower Bunch",
      "price": 35,
      "description": "A brilliant bunch of golden sunflowers.",
      "category": "Bunch",
      "type_id": 1,
      "colors": ["Yellow", "Green"],
      "occasion_ids": [4, 7, 8],
      "ratings_id": 8,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "classic-daisy-delight-vase",
      "name": "Classic Daisy Delight Vase",
      "price": 27,
      "description": "Fresh white daisies arranged simply in a vase.",
      "category": "Vase",
      "type_id": 1,
      "colors": ["White", "Green"],
      "occasion_ids": [5, 7],
      "ratings_id": 9,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "regal-blue-hydrangea-collection",
      "name": "Regal Blue Hydrangea Collection",
      "price": 65,
      "description": "A striking blue hydrangea arrangement.",
      "category": "Arrangement",
      "type_id": 1,
      "colors": ["Blue", "Green"],
      "occasion_ids": [10, 9, 4],
      "ratings_id": 10,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "petite-wildflower-wrap",
      "name": "Petite Wildflower Wrap",
      "price": 20,
      "description": "A small but charming wildflower wrap.",
      "category": "Wrap",
      "type_id": 3,
      "colors": ["Yellow", "Purple", "Green"],
      "occasion_ids": [7, 4],
      "ratings_id": 11,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "magnificent-orchid-trio",
      "name": "Magnificent Orchid Trio",
      "price": 90,
      "description": "Three elegant orchid stems in a beautiful display.",
      "category": "Arrangement",
      "type_id": 1,
      "colors": ["White", "Purple"],
      "occasion_ids": [10, 9, 4],
      "ratings_id": 12,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "scarlet-rose-extravaganza",
      "name": "Scarlet Rose Extravaganza",
      "price": 85,
      "description": "A luxurious collection of 24 red roses.",
      "category": "Bunch",
      "type_id": 1,
      "colors": ["Red", "Green"],
      "occasion_ids": [2, 1, 3],
      "ratings_id": 13,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "blush-peony-perfection",
      "name": "Blush Peony Perfection",
      "price": 62,
      "description": "A delightful peony bouquet in soft pink hues.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["Pink", "Green"],
      "occasion_ids": [8, 10, 2],
      "ratings_id": 14,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "summer-breeze-bouquet",
      "name": "Summer Breeze Bouquet",
      "price": 45,
      "description": "A cheerful seasonal flower arrangement.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["Yellow", "Red", "Green"],
      "occasion_ids": [4, 9],
      "ratings_id": 15,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "woodland-garden-delight",
      "name": "Woodland Garden Delight",
      "price": 50,
      "description": "A rustic garden-style arrangement with ferns.",
      "category": "Arrangement",
      "type_id": 5,
      "colors": ["Green", "Brown", "Yellow"],
      "occasion_ids": [7, 5],
      "ratings_id": 16,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "romantic-rose-tulip-bundle",
      "name": "Romantic Rose & Tulip Bundle",
      "price": 58,
      "description": "A sophisticated blend of roses and tulips.",
      "category": "Bundle",
      "type_id": 4,
      "colors": ["Red", "Pink", "Green"],
      "occasion_ids": [1, 2, 3],
      "ratings_id": 17,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "exotic-bird-of-paradise-display",
      "name": "Exotic Bird of Paradise Display",
      "price": 75,
      "description": "A tropical display featuring exotic Bird of Paradise blooms.",
      "category": "Display",
      "type_id": 1,
      "colors": ["Orange", "Green", "Yellow"],
      "occasion_ids": [9, 10],
      "ratings_id": 18,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "vibrant-gerbera-collection",
      "name": "Vibrant Gerbera Collection",
      "price": 38,
      "description": "A colorful mix of fresh gerberas.",
      "category": "Collection",
      "type_id": 1,
      "colors": ["Red", "Orange", "Pink"],
      "occasion_ids": [4, 7],
      "ratings_id": 19,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "lavender-serenity-bouquet",
      "name": "Lavender Serenity Bouquet",
      "price": 40,
      "description": "A calming lavender-themed floral arrangement.",
      "category": "Bouquet",
      "type_id": 1,
      "colors": ["Purple", "Green"],
      "occasion_ids": [6, 9],
      "ratings_id": 20,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "autumn-glow-arrangement",
      "name": "Autumn Glow Arrangement",
      "price": 60,
      "description": "An arrangement capturing the colors of autumn.",
      "category": "Arrangement",
      "type_id": 1,
      "colors": ["Orange", "Red", "Brown"],
      "occasion_ids": [5, 9],
      "ratings_id": 21,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "graceful-white-orchid-display",
      "name": "Graceful White Orchid Display",
      "price": 85,
      "description": "Elegant white orchids in a sophisticated display.",
      "category": "Display",
      "type_id": 1,
      "colors": ["White", "Green"],
      "occasion_ids": [3, 10],
      "ratings_id": 22,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "carnival-rose-twist",
      "name": "Carnival Rose Twist",
      "price": 68,
      "description": "A vibrant twist with roses in multiple hues.",
      "category": "Twist",
      "type_id": 1,
      "colors": ["Red", "Yellow", "Pink"],
      "occasion_ids": [8, 2],
      "ratings_id": 23,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    },
    {
      "slug": "delicate-baby-breath-wrap",
      "name": "Delicate Baby Breath Wrap",
      "price": 22,
      "description": "A gentle and elegant wrap of baby breath flowers.",
      "category": "Wrap",
      "type_id": 3,
      "colors": ["White"],
      "occasion_ids": [7, 4],
      "ratings_id": 24,
      "images": ["/images/Sunflowers.webp", "/images/Red Roses Bunch.webp"]
    },
    {
      "slug": "majestic-spring-bloom-vase",
      "name": "Majestic Spring Bloom Vase",
      "price": 78,
      "description": "A seasonal vase of vibrant spring blooms.",
      "category": "Vase",
      "type_id": 1,
      "colors": ["Pink", "Yellow", "Green"],
      "occasion_ids": [5, 7],
      "ratings_id": 25,
      "images": ["/images/Red Roses Bunch.webp", "/images/Sunflowers.webp"]
    }
  ],
  "types": [
    { "id": 1, "name": "fresh" },
    { "id": 2, "name": "artificial" },
    { "id": 3, "name": "dry" },
    { "id": 4, "name": "combo" },
    { "id": 5, "name": "greenery" },
    { "id": 6, "name": "fruit and sweet" },
    { "id": 7, "name": "other" }
  ],

  "occasions": [
    { "id": 1, "name": "Valentine's Day" },
    { "id": 2, "name": "Romance" },
    { "id": 3, "name": "Anniversary" },
    { "id": 4, "name": "Birthday" },
    { "id": 5, "name": "Get Well Soon" },
    { "id": 6, "name": "Funeral-Sympathy" },
    { "id": 7, "name": "Home Decor" },
    { "id": 8, "name": "Mother's Day" },
    { "id": 9, "name": "Corporate Event" },
    { "id": 10, "name": "Wedding" },
    { "id": 11, "name": "Thanksgiving" },
    { "id": 12, "name": "Graduation" },
    { "id": 13, "name": "Christmas" },
    { "id": 14, "name": "Housewarming" },
    { "id": 15, "name": "Celebration" },
    { "id": 16, "name": "Congratulations" },
    { "id": 17, "name": "Sad Occasion" },
    { "id": 18, "name": "Comemoration" },
    { "id": 19, "name": "Church" },
    { "id": 20, "name": "Unveiling" },
    { "id": 21, "name": "Goal Achievement" },
    { "id": 22, "name": "Missing You" },
    { "id": 23, "name": "Thank You" }
  ],

  "ratings": [
    { "id": 1, "average": 4.8, "count": 234 },
    { "id": 2, "average": 4.5, "count": 198 },
    { "id": 3, "average": 4.9, "count": 150 },
    { "id": 4, "average": 4.6, "count": 175 }
  ]
}

export default sampleData