const sampleData = {
  floral_arrangements: [
    {
      slug: 'rose-elegance-bouquet',
      name: 'Rose Elegance Bouquet',
      flower_type: [1, 4],
      price: 35,
      sale_price: 0,
      description: 'A stunning arrangement featuring fresh red roses.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'Green'],
      occasion_ids: [1, 2, 3],
      ratings_id: 1,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'sunflower-sunshine-bunch',
      name: 'Sunflower Sunshine Bunch',
      flower_type: [1, 4],
      price: 28,
      sale_price: 0,
      description: 'Bright yellow sunflowers arranged for a cheerful gift.',
      category: 'Bunch',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Yellow', 'Green'],
      occasion_ids: [4, 5],
      ratings_id: 2,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'pure-white-lily-grace',
      name: 'Pure White Lily Grace',
      flower_type: [1, 4],
      price: 42,
      sale_price: 0,
      description: 'An all-white lily bouquet symbolizing elegance.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['White', 'Green'],
      occasion_ids: [6, 7, 3],
      ratings_id: 3,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'pink-petal-romance-bunch',
      name: 'Pink Petal Romance Bunch',
      flower_type: [1, 4],
      price: 30,
      sale_price: 0,
      description: 'A charming collection of pink flowers.',
      category: 'Bunch',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Pink', 'Green'],
      occasion_ids: [2, 8, 4],
      ratings_id: 4,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'bright-carnival-bouquet',
      name: 'Bright Carnival Bouquet',
      flower_type: [1, 4],
      price: 25,
      sale_price: 0,
      description: 'Daisies and carnations in a playful mix of colors.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Yellow', 'Pink', 'White', 'Green'],
      occasion_ids: [4, 5, 9],
      ratings_id: 5,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'tropical-paradise-arrangement',
      name: 'Tropical Paradise Arrangement',
      flower_type: [1, 4],
      price: 70,
      sale_price: 0,
      description: 'Exotic flowers like Bird of Paradise and Heliconia.',
      category: 'Arrangement',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Orange', 'Yellow', 'Green', 'Red'],
      occasion_ids: [9, 10, 4],
      ratings_id: 6,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'sweetheart-rose-lily-combo',
      name: 'Sweetheart Rose & Lily Combo',
      flower_type: [1, 4],
      price: 48,
      sale_price: 0,
      description: 'A romantic mix of red roses and white lilies.',
      category: 'Combo',
      type_id: 4,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'White', 'Green'],
      occasion_ids: [2, 1, 3],
      ratings_id: 7,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'golden-sunset-sunflower-bunch',
      name: 'Golden Sunset Sunflower Bunch',
      flower_type: [1, 4],
      price: 35,
      sale_price: 0,
      description: 'A brilliant bunch of golden sunflowers.',
      category: 'Bunch',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Yellow', 'Green'],
      occasion_ids: [4, 7, 8],
      ratings_id: 8,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'classic-daisy-delight-vase',
      name: 'Classic Daisy Delight Vase',
      flower_type: [1, 4],
      price: 27,
      sale_price: 0,
      description: 'Fresh white daisies arranged simply in a vase.',
      category: 'Vase',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['White', 'Green'],
      occasion_ids: [5, 7],
      ratings_id: 9,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'regal-blue-hydrangea-collection',
      name: 'Regal Blue Hydrangea Collection',
      flower_type: [1, 4],
      price: 65,
      sale_price: 0,
      description: 'A striking blue hydrangea arrangement.',
      category: 'Arrangement',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Blue', 'Green'],
      occasion_ids: [10, 9, 4],
      ratings_id: 10,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'petite-wildflower-wrap',
      name: 'Petite Wildflower Wrap',
      flower_type: [1, 4],
      price: 20,
      sale_price: 0,
      description: 'A small but charming wildflower wrap.',
      category: 'Wrap',
      type_id: 3,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Yellow', 'Purple', 'Green'],
      occasion_ids: [7, 4],
      ratings_id: 11,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'magnificent-orchid-trio',
      name: 'Magnificent Orchid Trio',
      flower_type: [1, 4],
      price: 90,
      sale_price: 0,
      description: 'Three elegant orchid stems in a beautiful display.',
      category: 'Arrangement',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['White', 'Purple'],
      occasion_ids: [10, 9, 4],
      ratings_id: 12,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'scarlet-rose-extravaganza',
      name: 'Scarlet Rose Extravaganza',
      flower_type: [1, 4],
      price: 85,
      sale_price: 0,
      description: 'A luxurious collection of 24 red roses.',
      category: 'Bunch',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'Green'],
      occasion_ids: [2, 1, 3],
      ratings_id: 13,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'blush-peony-perfection',
      name: 'Blush Peony Perfection',
      flower_type: [1, 4],
      price: 62,
      sale_price: 0,
      description: 'A delightful peony bouquet in soft pink hues.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Pink', 'Green'],
      occasion_ids: [8, 10, 2],
      ratings_id: 14,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'summer-breeze-bouquet',
      name: 'Summer Breeze Bouquet',
      flower_type: [1, 4],
      price: 45,
      sale_price: 0,
      description: 'A cheerful seasonal flower arrangement.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Yellow', 'Red', 'Green'],
      occasion_ids: [4, 9],
      ratings_id: 15,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'woodland-garden-delight',
      name: 'Woodland Garden Delight',
      flower_type: [1, 4],
      price: 50,
      sale_price: 0,
      description: 'A rustic garden-style arrangement with ferns.',
      category: 'Arrangement',
      type_id: 5,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Green', 'Brown', 'Yellow'],
      occasion_ids: [7, 5],
      ratings_id: 16,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'romantic-rose-tulip-bundle',
      name: 'Romantic Rose & Tulip Bundle',
      flower_type: [1, 4],
      price: 58,
      sale_price: 0,
      description: 'A sophisticated blend of roses and tulips.',
      category: 'Bundle',
      type_id: 4,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'Pink', 'Green'],
      occasion_ids: [1, 2, 3],
      ratings_id: 17,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'exotic-bird-of-paradise-display',
      name: 'Exotic Bird of Paradise Display',
      flower_type: [1, 4],
      price: 75,
      sale_price: 0,
      description:
        'A tropical display featuring exotic Bird of Paradise blooms.',
      category: 'Display',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Orange', 'Green', 'Yellow'],
      occasion_ids: [9, 10],
      ratings_id: 18,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'vibrant-gerbera-collection',
      name: 'Vibrant Gerbera Collection',
      flower_type: [1, 4],
      price: 38,
      sale_price: 0,
      description: 'A colorful mix of fresh gerberas.',
      category: 'Collection',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'Orange', 'Pink'],
      occasion_ids: [4, 7],
      ratings_id: 19,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'lavender-serenity-bouquet',
      name: 'Lavender Serenity Bouquet',
      flower_type: [1, 4],
      price: 40,
      sale_price: 0,
      description: 'A calming lavender-themed floral arrangement.',
      category: 'Bouquet',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Purple', 'Green'],
      occasion_ids: [6, 9],
      ratings_id: 20,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'autumn-glow-arrangement',
      name: 'Autumn Glow Arrangement',
      flower_type: [1, 4],
      price: 60,
      sale_price: 0,
      description: 'An arrangement capturing the colors of autumn.',
      category: 'Arrangement',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Orange', 'Red', 'Brown'],
      occasion_ids: [5, 9],
      ratings_id: 21,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'graceful-white-orchid-display',
      name: 'Graceful White Orchid Display',
      flower_type: [1, 4],
      price: 85,
      sale_price: 0,
      description: 'Elegant white orchids in a sophisticated display.',
      category: 'Display',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['White', 'Green'],
      occasion_ids: [3, 10],
      ratings_id: 22,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'carnival-rose-twist',
      name: 'Carnival Rose Twist',
      flower_type: [1, 4],
      price: 68,
      sale_price: 0,
      description: 'A vibrant twist with roses in multiple hues.',
      category: 'Twist',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Red', 'Yellow', 'Pink'],
      occasion_ids: [8, 2],
      ratings_id: 23,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
    {
      slug: 'delicate-baby-breath-wrap',
      name: 'Delicate Baby Breath Wrap',
      flower_type: [1, 4],
      price: 22,
      sale_price: 0,
      description: 'A gentle and elegant wrap of baby breath flowers.',
      category: 'Wrap',
      type_id: 3,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['White'],
      occasion_ids: [7, 4],
      ratings_id: 24,
      images: ['/images/Sunflowers.webp', '/images/Red Roses Bunch.webp'],
    },
    {
      slug: 'majestic-spring-bloom-vase',
      name: 'Majestic Spring Bloom Vase',
      flower_type: [1, 4],
      price: 78,
      sale_price: 0,
      description: 'A seasonal vase of vibrant spring blooms.',
      category: 'Vase',
      type_id: 1,
      stock: 4,
      isFeatured: false,
      likes: 4,
      size: ['small', 'medium', 'large'],
      colors: ['Pink', 'Yellow', 'Green'],
      occasion_ids: [5, 7],
      ratings_id: 25,
      images: ['/images/Red Roses Bunch.webp', '/images/Sunflowers.webp'],
    },
  ],
  types: [
    { id: 1, name: 'fresh' },
    { id: 2, name: 'artificial' },
    { id: 3, name: 'dry' },
    { id: 4, name: 'combo' },
    { id: 5, name: 'greenery' },
    { id: 6, name: 'fruit and sweet' },
    { id: 7, name: 'other' },
  ],

  occasions: [
    { id: 1, name: "Valentine's Day" },
    { id: 2, name: 'Romance' },
    { id: 3, name: 'Anniversary' },
    { id: 4, name: 'Birthday' },
    { id: 5, name: 'Get Well Soon' },
    { id: 6, name: 'Funeral-Sympathy' },
    { id: 7, name: 'Home Decor' },
    { id: 8, name: "Mother's Day" },
    { id: 9, name: 'Corporate Event' },
    { id: 10, name: 'Wedding' },
    { id: 11, name: 'Thanksgiving' },
    { id: 12, name: 'Graduation' },
    { id: 13, name: 'Christmas' },
    { id: 14, name: 'Housewarming' },
    { id: 15, name: 'Celebration' },
    { id: 16, name: 'Congratulations' },
    { id: 17, name: 'Sad Occasion' },
    { id: 18, name: 'Comemoration' },
    { id: 19, name: 'Church' },
    { id: 20, name: 'Unveiling' },
    { id: 21, name: 'Goal Achievement' },
    { id: 22, name: 'Missing You' },
    { id: 23, name: 'Thank You' },
  ],

  ratings: [
    { id: 1, average: 4.8, count: 134 },
    { id: 2, average: 4.5, count: 18 },
    { id: 3, average: 4.9, count: 10 },
    { id: 4, average: 4.0, count: 23 },
    { id: 5, average: 3.9, count: 15 },
    { id: 6, average: 4.6, count: 36 },
    { id: 7, average: 4.1, count: 15 },
    { id: 8, average: 4.0, count: 25 },
    { id: 9, average: 4.9, count: 5 },
    { id: 10, average: 1.0, count: 1 },
    { id: 11, average: 3.9, count: 7 },
    { id: 12, average: 4.6, count: 17 },
    { id: 13, average: 2.9, count: 15 },
    { id: 14, average: 4.6, count: 2 },
    { id: 15, average: 3.8, count: 20 },
    { id: 16, average: 1.6, count: 16 },
    { id: 17, average: 0.0, count: 0 },
    { id: 18, average: 0.0, count: 0 },
    { id: 19, average: 0.0, count: 0 },
    { id: 20, average: 0.0, count: 3 },
    { id: 21, average: 3.6, count: 12 },
    { id: 22, average: 4.6, count: 14 },
    { id: 23, average: 4.7, count: 33 },
    { id: 24, average: 5.0, count: 2 },
    { id: 25, average: 4.9, count: 25 },
  ],

  colors: [
    { id: 1, name: 'Red' },
    { id: 2, name: 'Green' },
    { id: 3, name: 'Yellow' },
    { id: 4, name: 'White' },
    { id: 5, name: 'Pink' },
    { id: 6, name: 'Orange' },
    { id: 7, name: 'Purple' },
    { id: 8, name: 'Blue' },
    { id: 9, name: 'Brown' },
  ],

  flower_type: [
    {
      id: 1,
      name: 'Daisies',
    },
    {
      id: 2,
      name: 'Roses',
    },
    {
      id: 3,
      name: 'Carnations',
    },
    {
      id: 4,
      name: 'Chrysanthemums',
    },
    {
      id: 5,
      name: 'Lilies',
    },
    {
      id: 6,
      name: 'Lilacs',
    },
    {
      id: 7,
      name: 'Sunflowers',
    },
    {
      id: 8,
      name: 'Tulips',
    },
    {
      id: 9,
      name: 'Daliahs',
    },
    {
      id: 10,
      name: 'Proteas',
    },
    {
      id: 11,
      name: 'Gerberas',
    },
    {
      id: 12,
      name: 'Iris',
    },
    {
      id: 13,
      name: 'Orchards',
    },
  ],
};

export default sampleData